// src/components/Common/SelectInput.vue
<template>
  <div :class="`col-md-${col}`">
    <div class="form-group">
      <label>{{ label }}</label>
      <span v-if="helptext" class="form-help d-block mb-1 text-muted small">{{ helptext }}</span>
      <select class="form-control" v-model="selected">
        <option v-if="placeholder" value="">{{ placeholder }}</option>
        <option
          v-for="opt in normalizedOptions"
          :key="opt.value"
          :value="opt.value"
        >
          {{ opt.label }}
        </option>
      </select>
    </div>
  </div>
</template>

<script>
export default {
  name: 'SelectInput',
  props: {
    col: {
      type: Number,
      default: 6,
    },
    label: {
      type: String,
      default: '',
    },
    helptext: {
      type: String,
      default: '',
    },
    placeholder: {
      type: String,
      default: '— Select —',
    },
    /** String[] or { value, label }[] */
    options: {
      type: Array,
      default: () => [],
    },
    value: {
      type: String,
      default: '',
    },
  },
  computed: {
    normalizedOptions() {
      return this.options.map((o) =>
        typeof o === 'string' ? { value: o, label: o } : o
      );
    },
    selected: {
      get() {
        return this.value;
      },
      set(val) {
        this.$emit('input', val);
        this.$emit('change', val);
      },
    },
  },
};
</script>

// src/components/Common/SelectInput.jsx
import React from 'react';

/**
 * SelectInput
 * Props: { id, label, value, onChange, options=[], help='', placeholder='Select...' }
 * options can be string[] or { value, label }[]
 */
export default function SelectInput({
  id,
  label,
  value,
  onChange,
  options = [],
  help = '',
  placeholder = 'Select...',
}) {
  const normalizedOptions = options.map((opt) =>
    typeof opt === 'string' ? { value: opt, label: opt } : opt
  );

  return (
    <div className="mb-3">
      {label && (
        <label className="wpg-label form-label" htmlFor={id}>
          {label}
        </label>
      )}
      <select
        id={id}
        className="wpg-select form-select"
        value={value || ''}
        onChange={(e) => onChange(e.target.value)}
      >
        {placeholder && (
          <option value="" disabled>
            {placeholder}
          </option>
        )}
        {normalizedOptions.map((opt) => (
          <option key={opt.value} value={opt.value}>
            {opt.label}
          </option>
        ))}
      </select>
      {help && <div className="wpg-help form-text">{help}</div>}
    </div>
  );
}
